name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x app/gradlew

      - name: Build and run tests
        run: ./gradlew build jacocoTestReport
        working-directory: app

      - name: List JaCoCo report directory
        run: ls -la app/build/reports/jacoco/test

      - name: Upload Coverage to Code Climate
        run: |
          curl -X POST -F 'file=@app/build/reports/jacoco/test/jacocoTestReport.xml' \
          -H 'Content-Type: multipart/form-data' \
          -H 'Authorization: Token ${{secrets.CC_TEST_REPORTER_ID}}' \
          https://api.codeclimate.com/v1/test_reports
