name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Make gradlew executable
        run: chmod +x app/gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain
        working-directory: app

      - name: Run tests
        run: ./gradlew test
        working-directory: app

      - name: List JaCoCo report directory
        run: ls -la app/build/reports/jacoco/test

      - name: Build and run coverage report
        run: ./gradlew build jacocoTestReport
        working-directory: app

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

      - name: Upload Coverage to Code Climate
        run: |
          curl -X POST -F 'file=@app/build/reports/jacoco/test/jacocoTestReport.xml' \
          -H 'Content-Type: multipart/form-data' \
          -H 'Authorization: Token ${{secrets.CC_TEST_REPORTER_ID}}' \
          https://api.codeclimate.com/v1/test_reports
