name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List files in project directory for debug
        run: ls -la $GITHUB_WORKSPACE/app

      - name: Make gradlew executable
        run: chmod +x $GITHUB_WORKSPACE/app/gradlew

      - name: Build with Gradle
        run: $GITHUB_WORKSPACE/app/gradlew build
