name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x app/gradlew

      - name: Build and run tests
        run: ./gradlew build jacocoTestReport
        working-directory: app

      - name: Upload Coverage to Code Climate
        run: |
          curl -X POST -F 'file=@app/build/reports/jacoco/test/jacocoTestReport.xml' https://codeclimate.com/test_reports
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
